"""store mentor prefs

Revision ID: 2897ff863a4f
Revises: 7872f807b1fd
Create Date: 2018-08-21 20:10:25.755213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2897ff863a4f'
down_revision = '7872f807b1fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentee', sa.Column('mentor1', sa.String(length=128), nullable=True))
    op.add_column('mentee', sa.Column('mentor2', sa.String(length=128), nullable=True))
    op.add_column('mentee', sa.Column('mentor3', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mentee', 'mentor3')
    op.drop_column('mentee', 'mentor2')
    op.drop_column('mentee', 'mentor1')
    # ### end Alembic commands ###
