"""db init

Revision ID: 5815908e6898
Revises: 
Create Date: 2018-08-15 01:44:00.224992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5815908e6898'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('founder', sa.String(length=280), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('industry', sa.String(length=280), nullable=True),
    sa.Column('skills', sa.String(length=280), nullable=True),
    sa.Column('help_req', sa.String(length=280), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentee_email'), 'mentee', ['email'], unique=True)
    op.create_table('mentor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('about_me', sa.String(length=280), nullable=True),
    sa.Column('avail', sa.String(length=64), nullable=True),
    sa.Column('skill', sa.String(length=164), nullable=True),
    sa.Column('industry', sa.String(length=164), nullable=True),
    sa.Column('company', sa.String(length=164), nullable=True),
    sa.Column('position', sa.String(length=164), nullable=True),
    sa.Column('linked', sa.String(length=164), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentor_email'), 'mentor', ['email'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('mentor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_mentor_email'), table_name='mentor')
    op.drop_table('mentor')
    op.drop_index(op.f('ix_mentee_email'), table_name='mentee')
    op.drop_table('mentee')
    # ### end Alembic commands ###
