"""added preferred mentees

Revision ID: 5e8841430208
Revises: 927ec7bcccff
Create Date: 2019-01-16 22:23:45.350855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e8841430208'
down_revision = '927ec7bcccff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentor', sa.Column('mentee1', sa.String(length=128), nullable=True))
    op.add_column('mentor', sa.Column('mentee2', sa.String(length=128), nullable=True))
    op.add_column('mentor', sa.Column('mentee3', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mentor', 'mentee3')
    op.drop_column('mentor', 'mentee2')
    op.drop_column('mentor', 'mentee1')
    # ### end Alembic commands ###
