"""added acceptance

Revision ID: 69960197d1e8
Revises: 87568bb02895
Create Date: 2018-08-15 13:58:28.510219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69960197d1e8'
down_revision = '87568bb02895'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('accept', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'accept')
    # ### end Alembic commands ###
