"""added prefs

Revision ID: 6fea67b618df
Revises: 14d3c89a0856
Create Date: 2018-12-26 17:32:32.227113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fea67b618df'
down_revision = '14d3c89a0856'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentor', sa.Column('cohort_pref_id', sa.Integer(), nullable=True))
    op.add_column('mentor', sa.Column('mentee_pref_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mentor', 'cohort', ['cohort_pref_id'], ['id'])
    op.create_foreign_key(None, 'mentor', 'mentee', ['mentee_pref_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mentor', type_='foreignkey')
    op.drop_constraint(None, 'mentor', type_='foreignkey')
    op.drop_column('mentor', 'mentee_pref_id')
    op.drop_column('mentor', 'cohort_pref_id')
    # ### end Alembic commands ###
