"""making my own

Revision ID: b14d67bb98a5
Revises: 
Create Date: 2019-01-17 10:31:08.410774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b14d67bb98a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accept', sa.String(length=100), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('founder', sa.String(length=280), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('industry', sa.String(length=280), nullable=True),
    sa.Column('skills', sa.String(length=280), nullable=True),
    sa.Column('help_req', sa.String(length=280), nullable=True),
    sa.Column('interest', sa.String(length=500), nullable=True),
    sa.Column('gain', sa.String(length=500), nullable=True),
    sa.Column('stage', sa.String(length=100), nullable=True),
    sa.Column('relation', sa.String(length=280), nullable=True),
    sa.Column('web', sa.String(length=280), nullable=True),
    sa.Column('links', sa.String(length=380), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_email'), 'application', ['email'], unique=True)
    op.create_table('cohort',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('founder', sa.String(length=280), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('industry', sa.String(length=280), nullable=True),
    sa.Column('skills', sa.String(length=280), nullable=True),
    sa.Column('help_req', sa.String(length=280), nullable=True),
    sa.Column('mentor1', sa.String(length=128), nullable=True),
    sa.Column('mentor2', sa.String(length=128), nullable=True),
    sa.Column('mentor3', sa.String(length=128), nullable=True),
    sa.Column('mentor_pref_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mentor_pref_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cohort_email'), 'cohort', ['email'], unique=True)
    op.create_table('mentee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('founder', sa.String(length=280), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('industry', sa.String(length=280), nullable=True),
    sa.Column('skills', sa.String(length=280), nullable=True),
    sa.Column('help_req', sa.String(length=280), nullable=True),
    sa.Column('mentor1', sa.String(length=128), nullable=True),
    sa.Column('mentor2', sa.String(length=128), nullable=True),
    sa.Column('mentor3', sa.String(length=128), nullable=True),
    sa.Column('mentor_pref_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mentor_pref_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentee_email'), 'mentee', ['email'], unique=True)
    op.create_table('mentor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('about_me', sa.String(length=280), nullable=True),
    sa.Column('avail', sa.String(length=64), nullable=True),
    sa.Column('skill', sa.String(length=164), nullable=True),
    sa.Column('industry', sa.String(length=164), nullable=True),
    sa.Column('company', sa.String(length=164), nullable=True),
    sa.Column('position', sa.String(length=164), nullable=True),
    sa.Column('linked', sa.String(length=164), nullable=True),
    sa.Column('twitter', sa.String(length=164), nullable=True),
    sa.Column('mentee1', sa.String(length=128), nullable=True),
    sa.Column('mentee2', sa.String(length=128), nullable=True),
    sa.Column('mentee3', sa.String(length=128), nullable=True),
    sa.Column('mentee_pref_id', sa.Integer(), nullable=True),
    sa.Column('cohort_pref_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cohort_pref_id'], ['cohort.id'], ),
    sa.ForeignKeyConstraint(['mentee_pref_id'], ['mentee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentor_email'), 'mentor', ['email'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('email_hash', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('profile_pic', sa.String(length=188), nullable=True),
    sa.Column('access', sa.Integer(), nullable=True),
    sa.Column('mentor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_mentor_email'), table_name='mentor')
    op.drop_table('mentor')
    op.drop_index(op.f('ix_mentee_email'), table_name='mentee')
    op.drop_table('mentee')
    op.drop_index(op.f('ix_cohort_email'), table_name='cohort')
    op.drop_table('cohort')
    op.drop_index(op.f('ix_application_email'), table_name='application')
    op.drop_table('application')
    # ### end Alembic commands ###
