"""added app

Revision ID: cc8aaa3bc71e
Revises: b956c16c63c7
Create Date: 2018-08-15 02:02:46.499199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc8aaa3bc71e'
down_revision = 'b956c16c63c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('founder', sa.String(length=280), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('industry', sa.String(length=280), nullable=True),
    sa.Column('skills', sa.String(length=280), nullable=True),
    sa.Column('help_req', sa.String(length=280), nullable=True),
    sa.Column('interest', sa.String(length=500), nullable=True),
    sa.Column('gain', sa.String(length=500), nullable=True),
    sa.Column('stage', sa.String(length=100), nullable=True),
    sa.Column('relation', sa.String(length=280), nullable=True),
    sa.Column('web', sa.String(length=280), nullable=True),
    sa.Column('links', sa.String(length=380), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_email'), 'application', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_email'), table_name='application')
    op.drop_table('application')
    # ### end Alembic commands ###
