"""empty message

Revision ID: e779b9aafcc1
Revises: 453ac2e500da
Create Date: 2019-03-16 22:58:48.396576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e779b9aafcc1'
down_revision = '453ac2e500da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentee', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mentee', 'company', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mentee', type_='foreignkey')
    op.drop_column('mentee', 'company_id')
    # ### end Alembic commands ###
